# Generated by Django 5.0.3 on 2024-03-24 08:14

import app_transcription.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(default=app_transcription.models.generate_api, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to=app_transcription.models.file_path, validators=[django.core.validators.FileExtensionValidator(['opus', 'flac', 'webm', 'weba', 'wav', 'ogg', 'm4a', 'oga', 'mid', 'mp3', 'aiff', 'wma', 'au'])])),
                ('upload_date_time', models.DateTimeField(auto_now_add=True)),
                ('transcription_status', models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed')], default='Pending', max_length=50)),
                ('transcription_data', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date_time'],
            },
        ),
    ]
